/**
 * Every kind of record staff manage through the generic workspace screens.
 *
 * Each entry says which module it belongs to (and so who may read and change it — see
 * access/route-access.ts), which fields exist and how they are checked, and what the public
 * website may read. Records with their own workflow (accepting an application, confirming a
 * payment, marking attendance, taking an exam) have dedicated endpoints as well; the generic
 * screens cover looking them up and correcting details.
 */
import { BadRequestException } from "@nestjs/common";
import { certificateNumber, invoiceNumber, slugify, verificationCode } from "../common/codes";
import { nextStudentNumber } from "../students/student-number";
import { invoiceStatus } from "../finance/invoice-status";
import type { FieldDef, ResourceDef } from "./types";

const CEFR = ["A1", "A2", "B1", "B2", "C1", "C2"];
const LANGUAGES_HELP = "e.g. German, French, English";

/** Small helpers so each definition reads like a form. */
const f = {
  string: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "string", ...extra }),
  text: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "text", ...extra }),
  rich: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "richtext", ...extra }),
  email: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "email", ...extra }),
  phone: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "phone", ...extra }),
  url: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "url", ...extra }),
  image: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "image", ...extra }),
  file: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "file", ...extra }),
  int: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "int", ...extra }),
  number: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "number", ...extra }),
  money: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "money", min: 0, ...extra }),
  bool: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "bool", ...extra }),
  date: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "date", ...extra }),
  datetime: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "datetime", ...extra }),
  time: (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "time", ...extra }),
  enum: (name: string, label: string, options: string[], extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "enum", options, ...extra }),
  ref: (name: string, label: string, ref: string, relation: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: "ref", ref, relation, ...extra }),
};

/** Gives a record a unique URL slug from its title when none was typed. */
function withSlug(model: "course" | "newsPost") {
  return async (data: Record<string, unknown>, mode: "create" | "update", ctx: { prisma: any }, existing?: Record<string, unknown>) => {
    const title = (data.title ?? existing?.title) as string | undefined;
    if (mode === "create" || data.slug === "") {
      let slug = slugify(String(data.slug || title || ""));
      for (let n = 2; await ctx.prisma[model].findFirst({ where: { slug, NOT: { id: existing?.id ?? "" } }, select: { id: true } }); n++) {
        slug = `${slugify(String(data.slug || title || ""))}-${n}`;
      }
      data.slug = slug;
    }
    return data;
  };
}

export const RESOURCES: ResourceDef[] = [
  // ── Admissions ────────────────────────────────────────────────────────────
  {
    key: "applications",
    model: "application",
    label: "Applications",
    singular: "Application",
    description: "Online applications. Use Accept to create the student account, class place and first invoice in one step.",
    module: "admissions",
    titleField: "name",
    canCreate: false,
    deleteLevel: "manage",
    search: ["name", "email", "reference", "phone"],
    filters: ["status", "course", "level"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("reference", "Reference", { readOnly: true, list: true }),
      f.string("name", "Full name", { required: true, list: true }),
      f.email("email", "Email", { required: true, list: true }),
      f.phone("phone", "Phone"),
      f.string("course", "Course", { required: true, list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.enum("status", "Status", ["pending", "reviewing", "accepted", "waitlisted", "rejected"], { list: true }),
      f.date("dateOfBirth", "Date of birth"),
      f.string("gender", "Gender"),
      f.string("nationality", "Nationality"),
      f.text("address", "Address"),
      f.string("guardianName", "Guardian name"),
      f.phone("guardianPhone", "Guardian phone"),
      f.string("preferredSchedule", "Preferred schedule"),
      f.text("motivation", "Why they want to learn"),
      f.string("source", "How they heard about us"),
      f.file("paymentProofUrl", "Application fee proof"),
      f.text("notes", "Internal notes"),
      f.datetime("createdAt", "Submitted", { readOnly: true, list: true }),
    ],
  },
  {
    key: "enquiries",
    model: "enquiry",
    label: "Enquiries",
    singular: "Enquiry",
    description: "Everyone who asked about courses: website, walk-ins, calls and WhatsApp. Set a follow-up date so nobody is forgotten.",
    module: "admissions",
    titleField: "name",
    search: ["name", "email", "phone", "interest"],
    filters: ["status", "channel", "assignedToId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.phone("phone", "Phone", { list: true }),
      f.email("email", "Email"),
      f.string("interest", "Interested in", { list: true }),
      f.text("message", "Message"),
      f.enum("channel", "Channel", ["website", "walk-in", "phone", "whatsapp", "email", "social"], { default: "walk-in", list: true }),
      f.enum("status", "Status", ["new", "contacted", "follow_up", "converted", "closed"], { list: true }),
      f.ref("assignedToId", "Handled by", "staff", "assignedTo"),
      f.date("nextFollowUp", "Next follow-up", { list: true }),
      f.text("notes", "Notes"),
      f.datetime("createdAt", "Received", { readOnly: true }),
    ],
  },
  {
    key: "placement-results",
    model: "placementAttempt",
    label: "Placement tests",
    singular: "Placement test",
    description: "Results of the free online placement test.",
    module: "admissions",
    titleField: "name",
    canCreate: false,
    canUpdate: false,
    search: ["name", "email", "phone"],
    filters: ["language", "recommendedLevel"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { list: true, readOnly: true }),
      f.email("email", "Email", { list: true, readOnly: true }),
      f.phone("phone", "Phone", { readOnly: true }),
      f.string("language", "Language", { list: true, readOnly: true }),
      f.int("score", "Score", { list: true, readOnly: true }),
      f.int("total", "Out of", { readOnly: true }),
      f.string("recommendedLevel", "Recommended level", { list: true, readOnly: true }),
      f.datetime("createdAt", "Taken", { list: true, readOnly: true }),
    ],
  },
  {
    key: "exam-registrations",
    model: "examRegistration",
    label: "Exam registrations",
    singular: "Exam registration",
    description: "Candidates registered for official exams held at the institute.",
    module: "admissions",
    titleField: "name",
    search: ["name", "email", "passportNo"],
    filters: ["status", "sessionId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("sessionId", "Exam session", "exam-sessions", "session", { required: true, list: true }),
      f.string("name", "Candidate", { required: true, list: true }),
      f.email("email", "Email", { required: true, list: true }),
      f.phone("phone", "Phone"),
      f.date("dateOfBirth", "Date of birth"),
      f.string("passportNo", "Passport / ID number"),
      f.string("modules", "Modules"),
      f.file("paymentProofUrl", "Payment proof"),
      f.enum("status", "Status", ["pending", "confirmed", "cancelled", "sat"], { list: true }),
      f.string("result", "Result"),
    ],
  },

  // ── Students ──────────────────────────────────────────────────────────────
  {
    key: "students",
    model: "student",
    label: "Students",
    singular: "Student",
    description: "Every learner. New students receive an email to choose their portal password.",
    module: "students",
    titleField: "name",
    deleteLevel: "manage",
    cascades: true,
    pickerModules: ["finance", "academics", "teaching", "admissions", "communication"],
    search: ["name", "email", "studentNo", "phone"],
    filters: ["status", "course", "level"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("studentNo", "Student number", { readOnly: true, list: true }),
      f.string("name", "Full name", { required: true, list: true }),
      f.email("email", "Email", { required: true, list: true }),
      f.phone("phone", "Phone"),
      f.enum("status", "Status", ["active", "inactive", "suspended", "graduated"], { list: true }),
      f.string("course", "Course", { list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.date("dateOfBirth", "Date of birth"),
      f.string("gender", "Gender"),
      f.string("nationality", "Nationality"),
      f.text("address", "Address"),
      f.string("guardianName", "Guardian name"),
      f.phone("guardianPhone", "Guardian phone"),
      f.image("photoUrl", "Photo"),
      f.text("notes", "Notes"),
    ],
    prepare: async (data, mode, ctx) => {
      if (mode === "create") data.studentNo = await nextStudentNumber(ctx.prisma);
      if (typeof data.email === "string") data.email = data.email.toLowerCase();
      return data;
    },
  },
  {
    key: "enrollments",
    model: "enrollment",
    label: "Enrolments",
    singular: "Enrolment",
    description: "Which student is in which class.",
    module: "students",
    titleField: "id",
    filters: ["classId", "studentId", "status"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("studentId", "Student", "students", "student", { required: true, list: true }),
      f.ref("classId", "Class", "classes", "class", { required: true, list: true }),
      f.enum("status", "Status", ["active", "waitlisted", "completed", "dropped"], { list: true }),
      f.datetime("createdAt", "Enrolled", { readOnly: true, list: true }),
    ],
  },
  {
    key: "certificates",
    model: "certificate",
    label: "Certificates",
    singular: "Certificate",
    description: "Issued certificates. Anyone can check one on the website with its verification code.",
    module: "students",
    titleField: "certificateNo",
    deleteLevel: "manage",
    search: ["holderName", "certificateNo", "verificationCode", "course"],
    filters: ["revoked", "studentId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("certificateNo", "Certificate number", { readOnly: true, list: true }),
      f.string("verificationCode", "Verification code", { readOnly: true, list: true }),
      f.ref("studentId", "Student", "students", "student"),
      f.string("holderName", "Name on certificate", { required: true, list: true }),
      f.string("course", "Course", { required: true, list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.string("grade", "Grade"),
      f.int("hours", "Teaching hours", { min: 0 }),
      f.date("issuedAt", "Issued on"),
      f.bool("revoked", "Revoked", { list: true }),
    ],
    prepare: async (data, mode, ctx) => {
      if (mode === "create") {
        data.certificateNo = certificateNumber();
        data.verificationCode = verificationCode();
        if (!data.holderName && typeof data.studentId === "string") {
          const student = await ctx.prisma.student.findUnique({ where: { id: data.studentId }, select: { name: true } });
          data.holderName = student?.name;
        }
      }
      return data;
    },
  },
  {
    key: "skill-assessments",
    model: "skillAssessment",
    label: "Skill assessments",
    singular: "Skill assessment",
    description: "Reading, writing, listening and speaking scores (0–100) with the CEFR level reached.",
    module: "students",
    titleField: "term",
    filters: ["studentId", "term"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("studentId", "Student", "students", "student", { required: true, list: true }),
      f.string("term", "Term", { list: true }),
      f.number("reading", "Reading", { min: 0, max: 100, list: true }),
      f.number("writing", "Writing", { min: 0, max: 100, list: true }),
      f.number("listening", "Listening", { min: 0, max: 100, list: true }),
      f.number("speaking", "Speaking", { min: 0, max: 100, list: true }),
      f.enum("cefrLevel", "CEFR level", CEFR, { list: true }),
      f.text("comments", "Comments"),
    ],
    prepare: async (data, mode, ctx) => {
      if (mode === "create") data.assessedById = ctx.actor.id;
      return data;
    },
  },
  {
    key: "evaluations",
    model: "courseEvaluation",
    label: "Course evaluations",
    singular: "Course evaluation",
    description: "What students said about their course and teacher (1–5 stars).",
    module: "academics",
    titleField: "id",
    canCreate: false,
    canUpdate: false,
    filters: ["classId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("studentId", "Student", "students", "student", { readOnly: true, list: true }),
      f.string("classId", "Class", { readOnly: true }),
      f.int("courseRating", "Course", { readOnly: true, list: true }),
      f.int("teacherRating", "Teacher", { readOnly: true, list: true }),
      f.text("comments", "Comments", { readOnly: true, list: true }),
      f.datetime("createdAt", "Sent", { readOnly: true, list: true }),
    ],
  },

  // ── Academics ─────────────────────────────────────────────────────────────
  {
    key: "courses",
    model: "course",
    label: "Courses",
    singular: "Course",
    description: "Courses shown on the website and used for classes and fees.",
    module: "academics",
    titleField: "title",
    pickerModules: ["finance", "website", "admissions"],
    search: ["title", "language", "level"],
    filters: ["language", "published"],
    sort: { field: "position", dir: "asc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.string("slug", "Web address", { help: "Leave empty to make one from the title." }),
      f.string("language", "Language", { required: true, list: true, help: LANGUAGES_HELP }),
      f.enum("level", "Level", [...CEFR, "A1–A2", "A1–B2", "B1–B2", "All levels"], { list: true }),
      f.string("status", "Status label", { list: true, help: "e.g. Enrolling now, Starting soon, Full" }),
      f.string("schedule", "Schedule"),
      f.string("duration", "Duration"),
      f.string("feeText", "Fee as shown", { help: "e.g. MWK 150,000 per term" }),
      f.money("feeAmount", "Fee amount"),
      f.int("capacity", "Places", { min: 0 }),
      f.text("summary", "Short summary"),
      f.rich("body", "Full description"),
      f.image("image", "Picture"),
      f.int("position", "Order", { help: "Lower numbers show first." }),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: {
      where: { published: true },
      fields: ["id", "slug", "title", "language", "level", "status", "schedule", "duration", "feeText", "feeAmount", "capacity", "summary", "body", "image"],
      sort: { field: "position", dir: "asc" },
    },
    prepare: withSlug("course"),
  },
  {
    key: "classes",
    model: "classGroup",
    label: "Classes",
    singular: "Class",
    description: "Teaching groups: who teaches them, when and where.",
    module: "academics",
    titleField: "name",
    cascades: true,
    pickerModules: ["students", "finance", "teaching", "communication"],
    search: ["name", "room"],
    filters: ["status", "courseId", "teacherId", "level", "mode"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.ref("courseId", "Course", "courses", "course", { list: true }),
      f.ref("teacherId", "Teacher", "staff", "teacher", { list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.string("room", "Room"),
      f.string("schedule", "Schedule", { list: true }),
      f.enum("mode", "Mode", ["in-person", "online", "hybrid"]),
      f.url("meetingUrl", "Online class link", { help: "Google Meet, Zoom or Jitsi link for online lessons." }),
      f.date("startDate", "Starts"),
      f.date("endDate", "Ends"),
      f.int("maxStudents", "Maximum students", { min: 1 }),
      f.enum("status", "Status", ["planned", "active", "completed", "cancelled"], { list: true }),
    ],
  },
  {
    key: "timetable",
    model: "timetableEntry",
    label: "Timetable",
    singular: "Lesson slot",
    description: "Weekly lesson times for each class.",
    module: "academics",
    titleField: "startTime",
    filters: ["classId", "dayOfWeek"],
    sort: { field: "dayOfWeek", dir: "asc" },
    fields: [
      f.ref("classId", "Class", "classes", "class", { required: true, list: true }),
      f.int("dayOfWeek", "Day", {
        required: true,
        list: true,
        min: 0,
        max: 6,
        options: ["0", "1", "2", "3", "4", "5", "6"],
        optionLabels: { "0": "Sunday", "1": "Monday", "2": "Tuesday", "3": "Wednesday", "4": "Thursday", "5": "Friday", "6": "Saturday" },
      }),
      f.time("startTime", "Starts", { required: true, list: true }),
      f.time("endTime", "Ends", { required: true, list: true }),
      f.string("room", "Room", { list: true }),
    ],
  },
  {
    key: "assignments",
    model: "assignment",
    label: "Assignments",
    singular: "Assignment",
    module: "academics",
    titleField: "title",
    cascades: true,
    search: ["title"],
    filters: ["classId", "skill"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("classId", "Class", "classes", "class", { required: true, list: true }),
      f.string("title", "Title", { required: true, list: true }),
      f.rich("description", "Instructions"),
      f.file("attachmentUrl", "Attachment"),
      f.enum("skill", "Skill", ["reading", "writing", "listening", "speaking", "grammar", "vocabulary"], { list: true }),
      f.datetime("dueAt", "Due", { list: true }),
      f.int("totalPoints", "Points", { min: 1 }),
      f.bool("published", "Visible to students", { default: true }),
    ],
  },
  {
    key: "exams",
    model: "exam",
    label: "Exams & quizzes",
    singular: "Exam",
    description: "Online tests. Build the questions with the exam builder; choice questions are marked automatically.",
    module: "academics",
    titleField: "title",
    cascades: true,
    search: ["title"],
    filters: ["classId", "published"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("classId", "Class", "classes", "class", { list: true }),
      f.string("title", "Title", { required: true, list: true }),
      f.text("description", "Instructions"),
      f.datetime("opensAt", "Opens", { list: true }),
      f.datetime("closesAt", "Closes"),
      f.int("durationMinutes", "Time allowed (minutes)", { min: 1, max: 600 }),
      f.int("passMark", "Pass mark (%)", { min: 0, max: 100 }),
      f.bool("published", "Open to students", { list: true }),
      { name: "questions", label: "Questions", type: "json", hidden: true },
    ],
  },
  {
    key: "exam-sessions",
    model: "examSession",
    label: "Official exam sessions",
    singular: "Exam session",
    description: "Official exams (e.g. Goethe-Zertifikat) that candidates can register for on the website.",
    module: "academics",
    titleField: "title",
    cascades: true,
    pickerModules: ["admissions"],
    search: ["title", "provider"],
    filters: ["published", "level"],
    sort: { field: "examDate", dir: "asc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.string("provider", "Provider", { list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.string("modules", "Modules", { help: "e.g. Lesen, Hören, Schreiben, Sprechen" }),
      f.date("examDate", "Exam date", { required: true, list: true }),
      f.date("registrationDeadline", "Registration closes"),
      f.string("venue", "Venue"),
      f.money("fee", "Fee"),
      f.int("capacity", "Places", { min: 0 }),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: {
      where: { published: true },
      fields: ["id", "title", "provider", "level", "modules", "examDate", "registrationDeadline", "venue", "fee", "capacity"],
      sort: { field: "examDate", dir: "asc" },
    },
  },
  {
    key: "calendar",
    model: "calendarEvent",
    label: "Calendar",
    singular: "Calendar entry",
    description: "Terms, holidays, exam dates and events. Public entries appear on the website and in the calendar feed.",
    module: "academics",
    titleField: "title",
    search: ["title"],
    filters: ["type", "public"],
    sort: { field: "startDate", dir: "asc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.enum("type", "Type", ["term", "holiday", "exam", "event", "deadline"], { list: true }),
      f.date("startDate", "Starts", { required: true, list: true }),
      f.date("endDate", "Ends"),
      f.text("description", "Details"),
      f.bool("public", "Show on website", { list: true, default: true }),
    ],
    public: {
      where: { public: true },
      fields: ["id", "title", "type", "startDate", "endDate", "description"],
      sort: { field: "startDate", dir: "asc" },
      limit: 200,
    },
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    key: "fees",
    model: "fee",
    label: "Fee structure",
    singular: "Fee",
    module: "finance",
    titleField: "name",
    search: ["name"],
    filters: ["type", "courseId", "active"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.ref("courseId", "Course", "courses", "course", { list: true }),
      f.money("amount", "Amount", { required: true, list: true }),
      f.enum("frequency", "Charged", ["one-time", "monthly", "term", "yearly"], { list: true }),
      f.enum("type", "Type", ["tuition", "application", "exam", "materials", "late_fee", "other"], { list: true }),
      f.string("description", "Description"),
      f.bool("active", "In use", { default: true }),
    ],
  },
  {
    key: "invoices",
    model: "invoice",
    label: "Invoices",
    singular: "Invoice",
    description: "What each student owes. Payments confirmed by finance are applied automatically.",
    module: "finance",
    titleField: "invoiceNo",
    deleteLevel: "manage",
    search: ["invoiceNo", "description"],
    filters: ["status", "studentId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("invoiceNo", "Invoice", { readOnly: true, list: true }),
      f.ref("studentId", "Student", "students", "student", { required: true, list: true }),
      f.string("description", "Description", { required: true, list: true }),
      f.money("amount", "Amount", { required: true, list: true }),
      f.money("discount", "Discount / scholarship"),
      f.money("paid", "Paid", { readOnly: true, list: true }),
      f.date("dueDate", "Due", { list: true }),
      f.enum("status", "Status", ["pending", "partial", "paid", "overdue", "cancelled"], { list: true }),
    ],
    prepare: async (data, mode, _ctx, existing) => {
      if (mode === "create") data.invoiceNo = invoiceNumber();
      // Keep the status in step with the numbers unless someone is cancelling or re-opening it by hand.
      const merged = { amount: 0, discount: 0, paid: 0, dueDate: null, ...existing, ...data } as { amount: unknown; discount: unknown; paid: unknown; dueDate: Date | null; status?: string };
      if (data.status !== "cancelled") {
        data.status = invoiceStatus({ amount: Number(merged.amount), discount: Number(merged.discount ?? 0), paid: Number(merged.paid ?? 0), dueDate: merged.dueDate ? new Date(merged.dueDate) : null });
      }
      return data;
    },
  },
  {
    key: "payments",
    model: "payment",
    label: "Payments",
    singular: "Payment",
    description: "Payments reported by students or recorded at the office. Confirm to apply them to the invoice and issue a receipt.",
    module: "finance",
    titleField: "reference",
    canUpdate: false,
    deleteLevel: "manage",
    search: ["reference", "receiptNo"],
    filters: ["status", "method", "studentId", "invoiceId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("receiptNo", "Receipt", { readOnly: true, list: true }),
      f.ref("studentId", "Student", "students", "student", { required: true, list: true }),
      f.ref("invoiceId", "Invoice", "invoices", "invoice", { list: true }),
      f.money("amount", "Amount", { required: true, list: true }),
      f.enum("method", "Method", ["cash", "bank", "airtel", "tnm", "card"], { list: true }),
      f.string("reference", "Transaction reference"),
      f.text("note", "Note"),
      f.file("proofUrl", "Proof of payment"),
      f.enum("status", "Status", ["pending", "confirmed", "rejected"], { readOnly: true, list: true }),
      f.datetime("createdAt", "Received", { readOnly: true, list: true }),
    ],
  },
  {
    key: "scholarships",
    model: "scholarship",
    label: "Scholarships",
    singular: "Scholarship",
    module: "finance",
    titleField: "title",
    cascades: true,
    search: ["title"],
    filters: ["open"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.text("description", "Description"),
      f.text("criteria", "Who can apply"),
      f.money("amount", "Amount", { list: true }),
      f.date("deadline", "Deadline", { list: true }),
      f.bool("open", "Open for applications", { list: true, default: true }),
    ],
  },
  {
    key: "scholarship-applications",
    model: "scholarshipApplication",
    label: "Scholarship applications",
    singular: "Scholarship application",
    module: "finance",
    titleField: "id",
    canCreate: false,
    filters: ["status", "scholarshipId"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("scholarshipId", "Scholarship", "scholarships", "scholarship", { readOnly: true, list: true }),
      f.ref("studentId", "Student", "students", "student", { readOnly: true, list: true }),
      f.text("statement", "Statement", { readOnly: true }),
      f.enum("status", "Decision", ["pending", "awarded", "rejected"], { list: true }),
      f.datetime("createdAt", "Applied", { readOnly: true, list: true }),
    ],
  },

  // ── Communication ─────────────────────────────────────────────────────────
  {
    key: "announcements",
    model: "announcement",
    label: "Announcements",
    singular: "Announcement",
    description: "Notices for students, staff or everyone. Public ones also appear on the website.",
    module: "communication",
    titleField: "title",
    search: ["title"],
    filters: ["audience", "published"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.rich("body", "Message"),
      f.enum("audience", "Who sees it", ["all", "students", "staff", "public"], { list: true }),
      f.bool("pinned", "Pin to top", { list: true }),
      f.bool("published", "Published", { list: true, default: true }),
      f.date("expiresAt", "Hide after"),
    ],
    public: {
      where: { published: true, audience: "public" },
      fields: ["id", "title", "body", "pinned", "createdAt", "expiresAt"],
      sort: { field: "createdAt", dir: "desc" },
      limit: 20,
    },
    prepare: async (data, mode, ctx) => {
      if (mode === "create") data.createdBy = ctx.actor.name;
      return data;
    },
  },

  // ── Website ───────────────────────────────────────────────────────────────
  {
    key: "news",
    model: "newsPost",
    label: "News",
    singular: "News article",
    module: "website",
    titleField: "title",
    search: ["title", "category"],
    filters: ["category", "published"],
    sort: { field: "publishedAt", dir: "desc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.string("slug", "Web address", { help: "Leave empty to make one from the title." }),
      f.string("category", "Category", { list: true }),
      f.text("summary", "Summary"),
      f.rich("body", "Article"),
      f.image("image", "Picture"),
      f.datetime("publishedAt", "Publish date", { list: true }),
      f.bool("published", "Published", { list: true, default: true }),
    ],
    public: {
      where: { published: true },
      fields: ["id", "slug", "title", "category", "summary", "body", "image", "publishedAt"],
      sort: { field: "publishedAt", dir: "desc" },
    },
    prepare: withSlug("newsPost"),
  },
  {
    key: "gallery",
    model: "galleryItem",
    label: "Gallery",
    singular: "Photo",
    module: "website",
    titleField: "caption",
    search: ["caption", "category"],
    filters: ["category", "published"],
    sort: { field: "position", dir: "asc" },
    fields: [
      f.image("src", "Photo", { required: true, list: true }),
      f.string("caption", "Caption", { list: true }),
      f.string("category", "Category", { list: true }),
      f.int("position", "Order"),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: { where: { published: true }, fields: ["id", "src", "caption", "category"], sort: { field: "position", dir: "asc" }, limit: 300 },
  },
  {
    key: "documents",
    model: "downloadDocument",
    label: "Downloads",
    singular: "Document",
    description: "Brochures, forms and policies visitors can download.",
    module: "website",
    titleField: "title",
    search: ["title", "type"],
    filters: ["type", "published"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.string("type", "Type", { list: true, help: "e.g. Brochure, Form, Policy" }),
      f.text("description", "Description"),
      f.file("file", "File", { required: true }),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: { where: { published: true }, fields: ["id", "title", "type", "description", "file", "createdAt"], sort: { field: "createdAt", dir: "desc" } },
  },
  {
    key: "testimonials",
    model: "testimonial",
    label: "Testimonials",
    singular: "Testimonial",
    module: "website",
    titleField: "name",
    search: ["name", "course"],
    filters: ["published"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.string("course", "Course", { list: true }),
      f.text("body", "What they said", { required: true }),
      f.image("photo", "Photo"),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: { where: { published: true }, fields: ["id", "name", "course", "body", "photo"], sort: { field: "createdAt", dir: "desc" } },
  },
  {
    key: "faq",
    model: "faq",
    label: "FAQ",
    singular: "Question",
    description: "Frequently asked questions. The website assistant answers from these too.",
    module: "website",
    titleField: "question",
    search: ["question", "answer", "category"],
    filters: ["category", "published"],
    sort: { field: "position", dir: "asc" },
    fields: [
      f.string("question", "Question", { required: true, list: true, maxLength: 300 }),
      f.text("answer", "Answer", { required: true }),
      f.string("category", "Category", { list: true }),
      f.int("position", "Order"),
      f.bool("published", "Show on website", { list: true, default: true }),
    ],
    public: { where: { published: true }, fields: ["id", "question", "answer", "category"], sort: { field: "position", dir: "asc" } },
  },
  {
    key: "library",
    model: "libraryItem",
    label: "Library",
    singular: "Library item",
    description: "Books, audio, worksheets and links. Free items are open to everyone; the rest need a student sign-in.",
    module: "website",
    titleField: "title",
    search: ["title", "author", "language"],
    filters: ["language", "level", "type", "published", "free"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("title", "Title", { required: true, list: true }),
      f.string("author", "Author", { list: true }),
      f.string("language", "Language", { list: true }),
      f.enum("level", "Level", CEFR, { list: true }),
      f.enum("type", "Type", ["book", "audio", "video", "worksheet", "link"], { list: true }),
      f.file("fileUrl", "File or link"),
      f.image("coverUrl", "Cover"),
      f.text("description", "Description"),
      f.bool("free", "Free for everyone", { list: true, default: true }),
      f.bool("published", "Published", { list: true, default: true }),
      f.int("downloads", "Downloads", { readOnly: true, list: true }),
    ],
    // File links of members-only items are removed by the public controller.
    public: {
      where: { published: true },
      fields: ["id", "title", "author", "language", "level", "type", "fileUrl", "coverUrl", "description", "free"],
      sort: { field: "createdAt", dir: "desc" },
      limit: 500,
    },
  },
  {
    key: "alumni",
    model: "alumnus",
    label: "Alumni",
    singular: "Graduate",
    module: "students",
    titleField: "name",
    search: ["name", "course", "currentJob"],
    filters: ["graduationYear"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.email("email", "Email"),
      f.string("course", "Course", { list: true }),
      f.int("graduationYear", "Graduated", { list: true, min: 1990, max: 2100 }),
      f.string("currentJob", "Now working as", { list: true }),
      f.string("location", "Where"),
      f.text("story", "Story"),
    ],
  },

  // ── Assistant ─────────────────────────────────────────────────────────────
  {
    key: "knowledge",
    model: "knowledgeNote",
    label: "Assistant knowledge",
    singular: "Knowledge note",
    description: "Extra facts the website assistant may use: opening hours, payment details, directions, policies.",
    module: "assistant",
    titleField: "title",
    search: ["title", "body"],
    filters: ["active"],
    sort: { field: "updatedAt", dir: "desc" },
    fields: [
      f.string("title", "Topic", { required: true, list: true }),
      f.text("body", "What the assistant should know", { required: true, maxLength: 8000 }),
      f.bool("active", "In use", { list: true, default: true }),
      f.datetime("updatedAt", "Updated", { readOnly: true, list: true }),
    ],
  },

  // ── People ────────────────────────────────────────────────────────────────
  {
    key: "leave-requests",
    model: "leaveRequest",
    label: "Leave requests",
    singular: "Leave request",
    module: "hr",
    titleField: "type",
    canCreate: false,
    filters: ["status", "staffId", "type"],
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.ref("staffId", "Staff member", "staff", "staff", { readOnly: true, list: true }),
      f.enum("type", "Type", ["annual", "sick", "maternity", "study", "unpaid", "other"], { readOnly: true, list: true }),
      f.date("startDate", "From", { readOnly: true, list: true }),
      f.date("endDate", "To", { readOnly: true, list: true }),
      f.int("days", "Working days", { readOnly: true, list: true }),
      f.text("reason", "Reason", { readOnly: true }),
      f.enum("status", "Status", ["pending", "approved", "rejected", "cancelled"], { readOnly: true, list: true }),
      f.string("reviewedBy", "Decided by", { readOnly: true }),
      f.text("reviewNote", "Note", { readOnly: true }),
    ],
  },

  // ── System ────────────────────────────────────────────────────────────────
  {
    key: "apps",
    model: "externalApp",
    label: "Apps & links",
    singular: "App",
    description: "Google Workspace (Classroom, Drive, Meet), Moodle and other tools, shown as tiles in the portals.",
    module: "system",
    titleField: "name",
    search: ["name"],
    filters: ["audience", "active"],
    sort: { field: "position", dir: "asc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.url("url", "Address", { required: true, list: true }),
      f.string("description", "Description"),
      f.enum("icon", "Icon", ["grid", "book", "video", "folder", "calendar", "mail", "globe", "clipboard", "monitor", "link"]),
      f.enum("audience", "Shown to", ["all", "students", "staff"], { list: true }),
      f.bool("embed", "Open inside the portal", { help: "Only works for sites that allow embedding." }),
      f.int("position", "Order"),
      f.bool("active", "Active", { list: true, default: true }),
    ],
  },
  {
    key: "webhooks",
    model: "webhook",
    label: "Webhooks",
    singular: "Webhook",
    description: "Send a signed notice to another system when something happens (application received, payment confirmed…).",
    module: "system",
    titleField: "name",
    deleteLevel: "manage",
    sort: { field: "createdAt", dir: "desc" },
    fields: [
      f.string("name", "Name", { required: true, list: true }),
      f.url("url", "Address (https)", { required: true, list: true }),
      f.string("events", "Events", { help: "Comma-separated, e.g. application.created, payment.confirmed — or * for all.", list: true }),
      f.string("secret", "Signing secret", { readOnly: true }),
      f.bool("active", "Active", { list: true, default: true }),
      f.string("lastStatus", "Last delivery", { readOnly: true, list: true }),
    ],
    prepare: async (data, mode) => {
      if (mode === "create") {
        const { randomBytes } = await import("crypto");
        data.secret = randomBytes(32).toString("hex");
      }
      if (typeof data.url === "string" && !data.url.startsWith("https://")) {
        throw new BadRequestException("Webhook addresses must start with https://");
      }
      return data;
    },
  },
];

/** Staff records are managed by the Staff & access screens, but pickers (class teacher, enquiry owner) need to look them up. */
export const STAFF_PICKER = { key: "staff", model: "staff", titleField: "name" };

export const RESOURCE_MAP = new Map(RESOURCES.map((resource) => [resource.key, resource]));

export function getResource(key: string): ResourceDef | undefined {
  return RESOURCE_MAP.get(key);
}
